eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # URL du Eureka Server où ce microservice va s'enregistrer
server:
  port: 8070
spring:
  application:
    name: school
  config:
    import: optional:configserver://localhost:8888
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb2
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

application:
  config:
    students-url: http://localhost:8090/api/v1/students